---
kind: pipeline
type: exec
name: default
platform:
  os: linux
  arch: arm64
steps:
- name: clone
  commands:
  - pwd
  - git clone git@iohub.dev:lxsang/antd-lua-plugin.git
  - cd ./antd-lua-plugin && git checkout master
steps:
- name: build
  commands:
  - cd ./antd-lua-plugin
  - libtoolize
  - aclocal
  - autoconf
  - automake --add-missing
  - ./configure --prefix=/opt/cloud/cuser
  - make
  - make install
trigger:
  branch:
  - master
