include ../../../../var.mk

LIB_NAME=ann.$(LIB_EXT)
LIB_OBJ=ann.o

LIB_INC=-I./fann/src/include/
FANN_LIB_A=./fann/build/src/libdoublefann.a

LIB_CONF = $(FANN_LIB_A) $(FANN_INC)

include ../../lib.mk